services:
    linuxgsm:
        image: gameservermanagers/linuxgsm-docker
        container_name: lgsm-docker
        hostname: 'LGSM'
        network_mode: host
        volumes:
          - '/home/cody/podman/linuxgsm/lgsm:/home/linuxgsm'
        restart: always
